#!/bin/bash
echo "this will ensure that everything the Makefile needs, eg brew, pyenv, etc is installed."
echo "brew TBD"
cp ~/.zshrc ~/.zshrc.backup
brew install pyenv
brew install pyenv-virtualenv
echo \"export PYENV_ROOT="$HOME/.pyenv"\" >> ~/zshrc
echo \"command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"\" >> ~/.zshrc
echo \"eval "$(pyenv init -)"\" >> ~/.zshrc
echo \"eval "$(pyenv virtualenv-init -)"\" >> ~/.zshrc
# ?? echo  if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi\" >> ~/.zshrc
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
pyenv install 3.11
pyenv global 3.11
pip install pyscaffold
brew install bandit
brew install snyk
brew install doppler
